name: Cypress test and report

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
  pull_request:
    branches:
      - main

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        uses: cypress-io/github-action@v5
        with:
          runTests: false

      - name: Run linter
        run: npm run lint

      - name: Cypress run
        uses: cypress-io/github-action@v5
        continue-on-error: true
        with:
          install: false

      - name: Deploy report to GitHub Page
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: cypress/reports/html
